name: "Release"
on: workflow_dispatch

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    env:
      PYTHON_VERSION: 3.11
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        continue-on-error: true
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: LS
        run: ls -la
      - name: Install dependencies
        run: python3 -m pip install --upgrade build
      - name: Build project
        run: python3 -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
